AppOne/urls.py
from django.urls import path
from AppOne import views
# from AppOne.views import SchoolList

app_name = 'AppOne'

urlpatterns = [
    path('index/', views.index,name="app1_index"),
    path('student_list/', views.studentlist, name="student_list"),
    path('school_list/', views.schoollist, name="school_list"),
    path('contact_us/', views.contact, name="contact"),
    path('add_student/', views.add_student, name="add_student"),
    path('delete_student/<int:id>/', views.delete_student, name="delete_student"),
    path('edit_student/<int:id>/', views.edit_student, name="edit_student"),
    path('edit_school/<int:id>/', views.edit_school, name="edit_school"),
    path('user_register/', views.user_register, name="userRegister"),
    path('user_login/', views.user_login, name="userLogin"),
    path('user_logout/', views.user_logout, name="userLogout"),
    path('user_verify/', views.verify_user, name="verify_user"),
    path('api/school/', views.school_api),
    path('api/school/<int:pk>/', views.school_detail),
    path('api/student/', views.student_api),
    path('api/schools/', views.SchoolList.as_view()),
    path('api/school/<int:pk>', views.SchoolDetail.as_view()),

]

ProTwo/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from AppOne import urls as app1_url
from AppTwo import urls as app2_url
from PortfolioSujan import urls as portfolio_sujan_url
from ProTwo import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppOne/', include(app1_url)),
    path('AppTwo/', include(app2_url)),
    path('PortfolioSujan/', include(portfolio_sujan_url)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppOne/models.py
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_delete, post_save
# Create your models here.


class School(models.Model):
    name = models.CharField(max_length=50)
    student_count = models.IntegerField(null=False)

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=90)
    age = models.IntegerField(default=10,null=False)
    address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15,null=False)
    height = models.CharField(max_length=5,default='5.9')
    school = models.ForeignKey(School,on_delete=models.CASCADE,null=True)
    photo = models.ImageField(upload_to="profile_pics", null=True)


class UserProfile(models.Model):
    photo = models.ImageField(upload_to="user_photo")
    cv = models.FileField(upload_to="user_cv")
    phone_no = models.CharField(max_length=13)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class Items(models.Model):
    name = models.CharField(max_length=242, default="Buffer")
    quantity = models.IntegerField()


class Transaction(models.Model):
    item = models.ForeignKey(Items, on_delete=models.CASCADE)
    quantity_sold = models.IntegerField()


@receiver(post_save, sender=Transaction, dispatch_uid="update_items")
def update_items(sender, instance, **kwargs):
    instance.item.quantity -=instance.quantity_sold
    instance.item.save()

@receiver(post_delete, sender=Transaction, dispatch_uid="update_items_delete")
def increase_items(sender, instance, **kwargs):
    instance.item.quantity +=instance.quantity_sold
    instance.item.save()

AppOne/forms.py
from django import forms
from AppOne.models import Student, School, UserProfile
from django.contrib.auth.models import User


class Contact_us_form(forms.Form):
    email = forms.EmailField()
    phone_number = forms.IntegerField()
    query = forms.CharField(max_length=350)


class Student_form(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'


class SchoolForm(forms.ModelForm):
    class Meta:
        model = School
        fields = '__all__'


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['user']
        # fields = '__all__'


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        # fields = '__all__'
        fields = ('first_name', 'last_name', 'username', 'password', 'email')


class LoginForm(forms.Form):
    username = forms.CharField(max_length=554)
    password = forms.CharField(widget=forms.PasswordInput)

AppOne/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse, Http404
from django.shortcuts import render, HttpResponse, redirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from rest_framework.views import APIView
from rest_framework import status
from AppOne.models import Student
from AppOne.models import School
from AppOne.forms import Contact_us_form, Student_form, SchoolForm, UserForm, UserProfileForm, LoginForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
from AppOne.serializers import SchoolSerializer, StudentSerializer, StudentCreateSerializer


def index(request):
    # return HttpResponse('<h1>this is index of app one</h1>')
    return render(request, 'AppOne/index.html', context={"test_key": ["test1", "test2"]})


def login1(request):
    return HttpResponse('<h1>this is login of app one</h1>')


@login_required(login_url='/AppOne/user_login')
def studentlist(request):
    students = Student.objects.all()
    msgs = messages.get_messages(request)
    return render(request, 'AppOne/student_list.html',context={"students":students, "messages":msgs})


def schoollist(request):
    msgs = messages.get_messages(request)
    school = School.objects.all()
    return render(request, 'AppOne/school_list.html', context={"schools":school, "messages":msgs})

def contact(request):
    if request.method == 'GET':
        contact = Contact_us_form()
        return render(request, 'AppOne/contact_us_form.html', context={'contact_us_form':contact})
    else:
        contact_us_form = Contact_us_form(request.POST)
        if contact_us_form.is_valid():
            print("Email:", contact_us_form.cleaned_data['email'])
            print("Phone no:", contact_us_form.cleaned_data['phone_number'])
            print("Query:", contact_us_form.cleaned_data['query'])
            return HttpResponse("Submitted")
        else:
            return HttpResponse("error")


def add_student(request):
    if request.method == 'GET':
        student = Student_form()
        return render(request, 'AppOne/add_student.html', context={'form':student})
    else:
        student = Student_form(request.POST, request.FILES)
        if student.is_valid():
            student.save()
            return HttpResponse('student saved successfully')
        else:
            return HttpResponse('error')


def delete_student(request,id):
    st = Student.objects.get(id=id)
    st.delete()
    return HttpResponse("Student Deleted")

def edit_student(request, id):
    student = Student.objects.get(id=id)
    if request.method == "GET":
        st_form = Student_form(instance=student)
        return render(request, 'AppOne/edit_student.html',context={'form':st_form})
    else:
        st_form = Student_form(request.POST, request.FILES, instance=student)
        if st_form.is_valid():
            st_form.save()
            # student_list = Student.objects.all()
            # return render(request, 'AppOne')
            messages.success(request,"Your changes are saved")
            return redirect('student_list')


def edit_school(request, id):
    school = School.objects.get(id=id)
    if request.method == "GET":
        sc_form = SchoolForm(instance=school)
        return render(request, 'AppOne/edit_school.html', context={'form': sc_form})
    else:
        sc_form = SchoolForm(request.POST, instance=school)
        if sc_form.is_valid():
            sc_form.save()
            messages.success(request, "Your changes are saved")
            return redirect('school_list')


def user_register(request):
    if request.method == 'GET':
        user_form = UserForm()
        user_profile_form = UserProfileForm()
        return render(request, 'AppOne/user_registration.html', context={"user_form": user_form, "user_profile_form": user_profile_form})
    else:
        user = UserForm(request.POST)
        user = user.save()
        user.set_password(user.password)
        user.save()
        user_profile = UserProfileForm(request.POST, request.FILES)
        user_prof = user_profile.save(commit=False)
        user_prof.user = user
        user_prof.save()
        return HttpResponse(1)


def user_login(request):
    if request.method == "GET":
        login = LoginForm()
        return render(request, 'AppOne/login.html', context={"loginForm": login})


def user_logout(request):
    logout(request)
    messages.success(request, "User Logged-out !!!")
    return redirect('AppOne:userLogin')


def verify_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                messages.success(request, 'Login Successful')

                return redirect('AppOne:add_student')
            else:
                messages.warning(request, "Inactive User")
                return redirect('AppOne:userLogin')
        else:
            messages.warning(request, "User not found! error")
            return redirect('AppOne:userLogin')

@csrf_exempt
def school_api(request):
    if request.method == 'GET':
        school_all = School.objects.all()
        school_serialized = SchoolSerializer(school_all, many=True)
        return JsonResponse(school_serialized.data, safe=False)
    else:
        data =JSONParser().parse(request)
        print(data)
        serializer = SchoolSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)


@csrf_exempt
def school_detail(request, pk):
    try:
        school = School.objects.get(pk=pk)
    except School.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = SchoolSerializer(school)
        return JsonResponse(serializer.data)
    elif request.method == 'DELETE':
        school.delete()
        return HttpResponse(status=204)

    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = SchoolSerializer(school, data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data)
        return JsonResponse(serializer.errors,status=400)
    else:
        return HttpResponse(status=500)


@csrf_exempt
def student_api(request):
    if request.method == 'GET':
        student = Student.objects.all()
        student_serialized = StudentSerializer(student, many=True)
        return JsonResponse(student_serialized.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        student_serialized = StudentCreateSerializer(data=data)
        if student_serialized.is_valid():
            student_serialized.save()
            return JsonResponse(student_serialized.data, status=201)
        return HttpResponse(status=402)


class SchoolList(APIView):
    def get(self,request):
        school = School.objects.all()
        serializer = SchoolSerializer(school,many=True)
        return JsonResponse(serializer.data, safe=False)
    def post(self,request):
        serializer =SchoolSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data,status=201)
        return JsonResponse(serializer.errors, status=400)


class SchoolDetail(APIView):
    def get_object(self, pk):
        try:
            return School.objects.get(pk=pk)
        except School.DoesNotExist:
            raise Http404

    def get(self,request, pk):
        school = self.get_object(pk)
        serializer = SchoolSerializer(school)
        return JsonResponse(serializer.data)

    def put(self, request, pk):
        school = self.get_object(pk)
        serializer = SchoolSerializer(school, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data)
        return JsonResponse(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

templates/AppOne/add_student.html
{% extends 'base.html' %}
{% block title %}
    <title>Add Student Form</title>
{% endblock %}

{% block body %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>
{% endblock %}

templates/AppOne/contact_us_form.html
{% extends 'base.html' %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ contact_us_form }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/AppOne/edit_school.html
{% extends 'base.html' %}

{% block body %}
    <form method = "POST" >
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value = "Save Changes">
    </form>
{% endblock body %}

templates/AppOne/edit_student.html
{% extends 'base.html' %}

{% block body %}
    <form method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value = "Save Changes">
    </form>
{% endblock body %}

templates/AppOne/index.html
{% extends 'base.html' %}

{% block title %}
    <title>App1|index</title>
{% endblock %}

{% block body %}
    <h1>this is index page of app 1</h1>
    <button class="btn btn-success">hello</button>
{% endblock %}

templates/AppOne/login.html
{% extends 'base.html' %}

{% block title %}
    <title>Login</title>
{% endblock %}

{% block body %}
<div class="container jumbotron">
    <form method="POST" action="{% url 'AppOne:verify_user' %}">
        {% csrf_token %}
        <label>Username</label>
        <input type="text" name="username" class="form-control">
        <label>Password</label>
        <input type="password" name="password" class="form-control">
        <input type="submit" value="LOGIN" class="btn btn-dark">
    </form>
</div>
{% endblock %}

templates/AppOne/school_list.html
{% extends 'base.html' %}

{% block body %}



    <table class = "table table-dark table-hover">
        <thead>
            <th>id</th>
            <th>Name</th>
            <th>Student Count</th>
            <th>Delete</th>
            <th>Edit</th>
        </thead>
        <tbody>
            {% for school in schools %}
                <tr>
                    <td>{{ school.id }}</td>
                    <td>{{ school.name }}</td>
                    <td>{{ school.student_count }}</td>
                    <td><a href="{% url 'edit_school' id=school.id %}">Edit</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/AppOne/student_list.html
{% extends 'base.html' %}
{% block body %}
    {% if messages %}
        {% for msg in messages %}
            <div class="alert alert-{{ msg.tags }}">{{ msg }}</div>
        {% endfor %}
    {% endif %}
    <table class = "table table-dark table-hover">
        <thead>
            <th>id</th>
            <th>Name</th>
            <th>Address</th>
            <th>Age</th>
            <th>School</th>
            <th>Delete</th>
            <th>Edit</th>
        </thead>
        <tbody>
            {% for student in students %}
                <tr>
                    <td>{{ student.id }}</td>
                    <td>{{ student.name }}</td>
                    <td>{{ student.address }}</td>
                    <td>{{ student.age }}</td>
                    <td>{{ student.school }}</td>
                    <td> <a href="{% url 'AppOne:delete_student' id=student.id %}">delete</a> </td>
                    <td> <a href="{% url 'AppOne:edit_student' id=student.id %}">Edit</a> </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/AppOne/user_registration.html
{% extends 'base.html' %}

{% block title %}
    <title>Register User</title>
{% endblock %}

{% block body %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ user_profile_form.as_p }}
    <input type="submit" value="Save changes">
    </form>
{% endblock %}