AppOne/urls.py
from django.urls import path
from AppOne import views
# from AppOne.views import SchoolList

app_name = 'AppOne'

urlpatterns = [
    path('index/', views.index,name="app1_index"),
    path('student_list/', views.studentlist, name="student_list"),
    path('school_list/', views.schoollist, name="school_list"),
    path('contact_us/', views.contact, name="contact"),
    path('add_student/', views.add_student, name="add_student"),
    path('delete_student/<int:id>/', views.delete_student, name="delete_student"),
    path('edit_student/<int:id>/', views.edit_student, name="edit_student"),
    path('edit_school/<int:id>/', views.edit_school, name="edit_school"),
    path('user_register/', views.user_register, name="userRegister"),
    path('user_login/', views.user_login, name="userLogin"),
    path('user_logout/', views.user_logout, name="userLogout"),
    path('user_verify/', views.verify_user, name="verify_user"),
    path('api/school/', views.school_api),
    path('api/school/<int:pk>/', views.school_detail),
    path('api/student/', views.student_api),
    path('api/schools/', views.SchoolList.as_view()),
    path('api/school/<int:pk>', views.SchoolDetail.as_view()),

]

ProTwo/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from AppOne import urls as app1_url
from AppTwo import urls as app2_url
from PortfolioSujan import urls as portfolio_sujan_url
from ProTwo import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppOne/', include(app1_url)),
    path('AppTwo/', include(app2_url)),
    path('PortfolioSujan/', include(portfolio_sujan_url)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base-portfolio-sujan.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="{% static 'imgages/favicon.png'%}" type="image/png">
        {% block title %}
            <title>Title</title>
        {% endblock %}
    <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/lightbox/simpleLightbox.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/flaticon/flaticon.css' %}">
        <!-- main css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body >

<!--================Header Menu Area =================-->
        <header class="header_area">
            <div class="main_menu" id="mainNav">
            	<nav class="navbar navbar-expand-lg navbar-light">
					<div class="container box_1620">
						<!-- Brand and toggle get grouped for better mobile display -->
						<a class="navbar-brand logo_h" href="{% url 'portfolio_sujan_home' %}"><b>SUJAN KUMAL</b></a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
							<ul class="nav navbar-nav menu_nav ml-auto">
								<li class="nav-item active"><a class="nav-link" href="{% url 'portfolio_sujan_home' %}">Home</a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'portfolio_sujan_education' %} ">Education</a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'portfolio_sujan_photos' %}">Photos</a>

								<li class="nav-item"><a class="nav-link" href="{% url 'portfolio_sujan_contact' %}">Contact</a></li>
							</ul>
						</div>
					</div>
            	</nav>
            </div>
        </header>
        <!--================Header Menu Area =================-->




    {% block body %}
    {% endblock %}
<!--================Footer Area =================-->
        <div class="container">
            <br>
        </div>
        <footer class="footer_area ">
        	<br>

            <div class="container">
        		<div class="row footer_inner">
        			<div class="col-lg-5 col-sm-6">
        				<aside class="f_widget ab_widget">
        					<div class="f_title">
        						<h3>About Me</h3>
        					</div>
        					<p>“We all are stories in the end, so let's make it a good one.”</p>
        			    </aside>
        			</div>
        			<div class="col-lg-2 ">
        				<aside class="f_widget social_widget">
        					<div class="f_title">
        						<h3>Follow Me</h3>
        					</div>
        					<p>Let us be social</p>
        					<ul class="list">
        						<li><a href="https://www.facebook.com/sujan.kumal.03"><i class="fa fa-facebook"></i></a></li>
        						<li><a href="#"><i class="fa fa-twitter"></i></a></li>
        						<li><a href="https://www.instagram.com/sujan_03_"><i class="fa fa-instagram"></i></a></li>
        					</ul>
        				</aside>
        			</div>
        		</div>
        	</div>
        </footer>
        <!--================End Footer Area =================-->


        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
{#        <script src="{% static 'js/popper.js'%}"></script>#}
        <script src="{% static 'js/bootstrap.min.js'%}"></script>
{#        <script src="{% static 'js/stellar.js'%}"></script>#}
{#        <script src="{% static 'vendors/lightbox/simpleLightbox.min.js'%}"></script>#}
{#        <script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js'%}"></script>#}
{#        <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js'%}"></script>#}
{#        <script src="{% static 'vendors/isotope/isotope-min.js'%}"></script>#}
{#        <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js'%}"></script>#}
{#        <script src="{% static 'js/jquery.ajaxchimp.min.js'%}"></script>#}
{#        <script src="{% static 'vendors/counter-up/jquery.waypoints.min.js'%}"></script>#}
{#        <script src="{% static 'vendors/counter-up/jquery.counterup.min.js'%}"></script>#}
{#        <script src="{% static 'js/mail-script.js'%}"></script>#}
        <!--gmaps Js-->
{#        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>#}
{#        <script src="{% static 'js/gmaps.min.js'%}"></script>#}
{#        <script src="{% static 'js/theme.js'%}"></script>#}
</body>

</html>

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block title %}
    <title>Title</title>
    {% endblock %}


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<!--  -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'AppOne:app1_index' %}">App1 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app2_index' %}">App2</a>
      </li>
        {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'AppOne:userLogout' %}">Logout</a>
          </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'AppOne:userRegister' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'AppOne:userLogin' %}">Login</a>
              </li>
        {% endif %}

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


    {% if messages %}
        {% for msg in messages %}
            <div class="alert alert-{% if msg.tag == "error" %}danger{% else %}{{ msg.tags }}">{{ msg }}{% endif %}</div>
        {% endfor %}
    {% endif %}

{% block body %}
{% endblock %}


        <script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
        <script src="{% static 'js/popper.js'%}"></script>
        <script src="{% static 'js/bootstrap.min.js'%}"></script>
</body>

</html>